name: RifatCamPro
options:
  bundleIdPrefix: com.rifatcam
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: ""

targets:
  RifatCamPro:
    type: application
    platform: iOS
    sources:
      - path: RifatCamPro
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rifatcam.pro
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    info:
      path: RifatCamPro/Info.plist
